### PR TITLE
Check that money/small money are within correct range for bulkcopy

### LINKED ISSUE #2309: When I try to insert the value beyond the range, it inserting wrong values with small money/money.
## Driver version
JDBC driver version: 11.2.0.jre11, and the same behavior persists with the latest driver.

## SQL Server version
Microsoft SQL Azure (RTM) - 12.0.2000.8

## Client Operating System
Linux

## JAVA/JVM version
JAVA 11.

## Table schema
I have a table with only two columns: one of type smallmoney and the other of type money.
Screenshot from 2024-01-30 15-44-51
Screenshot from 2024-01-30 15-45-05

## Problem description
Azure SQL Support money and small money. The Range is money -922,337,203,685,477.5808 to 922,337,203,685,477.5807 Small Money 214,748.3648 to 214,748.3647. When we try to insert the value beyond the range, it inserting wrong values.
When I try to insert the value beyond the range, application is not failing instead its inserting like below. 

I try to Update              -214758.3648             922337203685487.5808
Bulk Load Updated to  -214738.3649             922337203685467.5808

I try to Update               214758.3647             922337203685487.5807
Bulk Load Updated to   214738.3648            -922337203685467.5809

When attempting to insert values beyond the allowed range, the operation results in the insertion of inaccurate values. I have an application where I perform batch insert operations, and it functions as intended. However, during bulk load operations using SQLServerBulkCopy, it inserts invalid values instead of failing. Upon debugging the mssql-jdbc jar code, I identified that this issue occurs internally within the convertMoneyToBytes() method of the DDC class in the com.microsoft.sqlserver.jdbc package. This method converts the provided values to the unscaled value of BigInteger and then to int or long values. Unfortunately, this process leads to complications when the given value surpasses the range of the corresponding int or long data type, resulting in the insertion of incorrect value.

## Expected behavior
It will throw an arithmetic overflow exception.

## Actual behavior
Inserting the wrong values.

## Error message/stack trace
No stacktrace as it not failing.

## Any other details that can be helpful
I have replicated the same behaviour in the standalone application - https://github.com/Aravind-Koonapureddy/AzureSqlTest/tree/main

## JDBC trace logs
No stacktrace as it not failing.

### PR DESCRIPTION
**Pull request by Jeffery-Wasty**
Fixes #2309

### CODE REVIEW

File: src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyMoneyTest.java [hunk 1]
```diff
@@ -0,0 +1,115 @@
...
+import org.junit.jupiter.api.Test;
+import org.junit.platform.runner.JUnitPlatform;
+import org.junit.runner.RunWith;
+
+import com.microsoft.sqlserver.testframework.AbstractSQLGenerator;
+import com.microsoft.sqlserver.testframework.AbstractTest;
+import com.microsoft.sqlserver.testframework.PrepUtil;
+
+
+/**
```
Comment (tkyc) [inline src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyMoneyTest.java:31]: Empty comment

File: src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyMoneyTest.java [hunk 2]
```diff
@@ -0,0 +1,115 @@
...
+ *
+ *
+ */
+@RunWith(JUnitPlatform.class)
+public class BulkCopyMoneyTest extends AbstractTest {
+    static String encoding = "UTF-8";
+    static String delimiter = ",";
```
Comment (lilgreenbird) [inline src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyMoneyTest.java:38]: COMMA in Constants

File: src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyMoneyTest.java [hunk 3]
```diff
@@ -0,0 +1,115 @@
...
+import com.microsoft.sqlserver.testframework.PrepUtil;
+
+
+/**
+ *
+ *
+ */
+@RunWith(JUnitPlatform.class)
+public class BulkCopyMoneyTest extends AbstractTest {
+    static String encoding = "UTF-8";
```
Comment (lilgreenbird) [inline src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyMoneyTest.java:37]: since this is now used in multiple places, add this to Constants where COMMA is defined?

File: src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyMoneyTest.java [hunk 4]
```diff
@@ -0,0 +1,115 @@
...
+        return fileRecord;
+    }
+
+    private void testMoneyWithBulkCopy(Connection conn, SQLServerBulkCSVFileRecord fileRecord) throws SQLException {
+        try (SQLServerBulkCopy bulkCopy = new SQLServerBulkCopy(conn); Statement stmt = conn.createStatement()) {
+
+            fileRecord.addColumnMetadata(1, "c1", java.sql.Types.DECIMAL, 10, 4); // with smallmoney
+            fileRecord.addColumnMetadata(2, "c2", java.sql.Types.DECIMAL, 19, 4); // with money
+
+
```
Comment (lilgreenbird) [inline src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyMoneyTest.java:91]: nitpick: extra line

File: src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyMoneyTest.java [hunk 5]
```diff
@@ -0,0 +1,115 @@
...
+            bulkCopy.setDestinationTableName(destTableName);
+            bulkCopy.writeToServer(fileRecord);
+
+            try (ResultSet rs = stmt.executeQuery("select * FROM " + destTableName + " order by c1");
+                    SQLServerBulkCopy bcOperation = new SQLServerBulkCopy(conn);) {
+                bcOperation.setDestinationTableName(destTableName2);
+                bcOperation.writeToServer(rs);
+            }
+
```
Comment (lilgreenbird) [inline src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyMoneyTest.java:100]: nitpick: extra line

**Review by barryw-mssql — APPROVED** [review]

File: src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyMoneyTest.java [hunk 6]
```diff
@@ -0,0 +1,115 @@
...
+        for (Map.Entry entry : data.entrySet()) {
+            stringBuilder.append(
+                    String.format("%s,%s\n", entry.getKey(), entry.getValue()));
+        }
+
+        byte[] bytes = stringBuilder.toString().getBytes(StandardCharsets.UTF_8);
+        SQLServerBulkCSVFileRecord fileRecord = null;
+        try (InputStream inputStream = new ByteArrayInputStream(bytes)) {
+            fileRecord = new SQLServerBulkCSVFileRecord(inputStream, encoding, delimiter, true);
+        } catch (IOException e) {}
```
Comment (lilgreenbird) [inline src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyMoneyTest.java:81]: shouldn't we fail?

File: src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyMoneyTest.java [hunk 7]
```diff
@@ -0,0 +1,115 @@
...
+            try (ResultSet rs = stmt.executeQuery("select * FROM " + destTableName + " order by c1");
+                    SQLServerBulkCopy bcOperation = new SQLServerBulkCopy(conn);) {
+                bcOperation.setDestinationTableName(destTableName2);
+                bcOperation.writeToServer(rs);
+            }
+
+        }
+    }
+
+    private void beforeEachSetup() throws SQLException {
```
Comment (lilgreenbird) [inline src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyMoneyTest.java:104]: y not use BeforeEach and also the tables are not deleted

File: src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyMoneyTest.java [hunk 8]
```diff
@@ -0,0 +1,115 @@
...
+import org.junit.platform.runner.JUnitPlatform;
+import org.junit.runner.RunWith;
+
+import com.microsoft.sqlserver.testframework.AbstractSQLGenerator;
+import com.microsoft.sqlserver.testframework.AbstractTest;
+import com.microsoft.sqlserver.testframework.PrepUtil;
+
+
+/**
+ *
```
Comment (lilgreenbird) [inline src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyMoneyTest.java:32]: empty comments

**Review by lilgreenbird — CHANGES_REQUESTED** [review]
please run formatter

**Review by tkyc — DISMISSED** [review]

File: src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyMoneyTest.java (hunk 7 above)
Comment (Jeffery-Wasty) [reply src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyMoneyTest.java]: Done

File: src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyMoneyTest.java (hunk 8 above)
Comment (Jeffery-Wasty) [reply src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyMoneyTest.java]: Addressed

File: src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyMoneyTest.java (hunk 6 above)
Comment (Jeffery-Wasty) [reply src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyMoneyTest.java]: Sorry for resolving earlier, now properly resolved.

**Review by lilgreenbird — APPROVED** [review]

**Review by barryw-mssql — APPROVED** [review]
