### PR TITLE
Fix | Fix SharedTimer implementation to use class level lock for thread safety

### LINKED ISSUE #1040: Hikari + MSSQL 7.2.1 having issues
Hello All,

We have an spring boot application that is using HikariCP and mssql 6.x libraries and everything seems working fine.

We started moving to the latest version of mssql, which is 7.2.1 and started observing issues connecting to the database, once in a while under load test.

On the initial research, we found that the SharedTimer thingy that got introduced is killing us.

`2019-04-17_00:27:40.315 [42122f1e7f861f55:42122f1e7f861f55:0] [Root=1-5cb672fb-8a9936f01f1e83407ebf0024] [qtp1673605040-61] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-278 - Exception during pool initialization.
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@746dc536 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7dd4eba[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at com.microsoft.sqlserver.jdbc.SharedTimer.schedule(SharedTimer.java:102)`

Any help on how to fix is highly appreciated.

### PR DESCRIPTION
**Pull request by cheenamalhotra**
Fixes #1040

### CODE REVIEW

File: src/main/java/com/microsoft/sqlserver/jdbc/SharedTimer.java [hunk 1]
```diff
@@ -56,16 +58,18 @@ static synchronized boolean isRunning() {
...
-            executor.shutdownNow();
-            executor = null;
-            instance = null;
+    public void removeRef() {
+        synchronized (lock) {
+            if (refCount.get() <= 0) {
+                throw new IllegalStateException("removeRef() called more than actual references");
+            }
+            refCount.getAndDecrement();
+            if (refCount.get() == 0) {
```
Comment (eugeniyk) [inline src/main/java/com/microsoft/sqlserver/jdbc/SharedTimer.java]: you'd better to use result that was returned by `refCount.getAndDecrement()`

File: src/main/java/com/microsoft/sqlserver/jdbc/SharedTimer.java [hunk 2]
```diff
@@ -77,11 +81,13 @@ public synchronized void removeRef() {
      * When the caller is finished with the SharedTimer it must be released via {@link#removeRef}
      */
     public static synchronized SharedTimer getTimer() {
```
Comment (sehrope) [inline src/main/java/com/microsoft/sqlserver/jdbc/SharedTimer.java]: The `synchronized` on the static method is no longer required here as its being manually managed via the `lock` object.

File: src/main/java/com/microsoft/sqlserver/jdbc/SharedTimer.java [hunk 3]
```diff
@@ -77,11 +81,13 @@ public synchronized void removeRef() {
...
-            instance = new SharedTimer();
+        synchronized (lock) {
+            if (instance == null) {
+                // No shared object exists so create a new one
+                instance = new SharedTimer();
+            }
+            instance.refCount.getAndIncrement();
         }
-        instance.refCount += 1;
         return instance;
```
Comment (sehrope) [inline src/main/java/com/microsoft/sqlserver/jdbc/SharedTimer.java]: The `return instance;` should be moved up into the `synchronized (lock) {...}` block. Otherwise there's a potential race condition if the instance is cleared by a concurrent call to `removeRef()` that completes after this synchronized block completes but prior to this method returning the value of `instance`.

File: src/main/java/com/microsoft/sqlserver/jdbc/SharedTimer.java [hunk 4]
```diff
@@ -16,10 +17,11 @@
      * Always update serialVersionUID when prompted
      */
     private static final long serialVersionUID = -4069361613863955760L;
-    
+
     static final String CORE_THREAD_PREFIX = "mssql-jdbc-shared-timer-core-";
     private static final AtomicLong CORE_THREAD_COUNTER = new AtomicLong();
-    private static SharedTimer instance;
+    private static volatile SharedTimer instance;
+    private static Object lock = new Object();
```
Comment (sehrope) [inline src/main/java/com/microsoft/sqlserver/jdbc/SharedTimer.java]: This should be final as it must never change.

Could also reorder it above the SharedTimer so that the final fields come before all non-final fields.

**Comment by sehrope** [comment]
The static `isRunning()` method should be updated to use the explicit lock object as well.

**Comment by sehrope** [comment]
Actually maybe it doesn't need the explicit synchronized lock at all as it's accessing the volatile field.

The method level synchronized can be removed though as the only thing it would be synchronizing is concurrent callers to that one method.

File: src/main/java/com/microsoft/sqlserver/jdbc/SharedTimer.java [hunk 5]
```diff
@@ -56,16 +59,17 @@ static synchronized boolean isRunning() {
...
-        refCount -= 1;
-        if (refCount == 0) {
-            // Removed last reference so perform cleanup
-            executor.shutdownNow();
-            executor = null;
-            instance = null;
+    public void removeRef() {
+        synchronized (lock) {
+            if (refCount.get() <= 0) {
+                throw new IllegalStateException("removeRef() called more than actual references");
```
Comment (ulvii) [inline src/main/java/com/microsoft/sqlserver/jdbc/SharedTimer.java]: @cheenamalhotra , shouldn't this be a `SQLServerException` instead?

File: src/main/java/com/microsoft/sqlserver/jdbc/SharedTimer.java [hunk 6]
```diff
@@ -56,16 +59,17 @@ static synchronized boolean isRunning() {
...
-        if (refCount <= 0) {
-            throw new IllegalStateException("removeRef() called more than actual references");
-        }
-        refCount -= 1;
-        if (refCount == 0) {
-            // Removed last reference so perform cleanup
-            executor.shutdownNow();
-            executor = null;
-            instance = null;
+    public void removeRef() {
```
Comment (ulvii) [inline src/main/java/com/microsoft/sqlserver/jdbc/SharedTimer.java]: `removeRef()` doesn't have to be `public`.

File: src/main/java/com/microsoft/sqlserver/jdbc/SharedTimer.java [hunk 7]
```diff
@@ -76,13 +80,15 @@ public synchronized void removeRef() {
      *
      * When the caller is finished with the SharedTimer it must be released via {@link#removeRef}
      */
-    public static synchronized SharedTimer getTimer() {
-        if (instance == null) {
-            // No shared object exists so create a new one
-            instance = new SharedTimer();
+    public static SharedTimer getTimer() {
```
Comment (ulvii) [inline src/main/java/com/microsoft/sqlserver/jdbc/SharedTimer.java]: Please remove `public`.

File: src/main/java/com/microsoft/sqlserver/jdbc/SharedTimer.java (hunk 6 above)
Comment (cheenamalhotra) [reply src/main/java/com/microsoft/sqlserver/jdbc/SharedTimer.java]: The class 'SharedTimer' is a package level class, these methods are not accessible to public eitherway. I didn't modify any implementation so this stayed.

File: src/main/java/com/microsoft/sqlserver/jdbc/SharedTimer.java (hunk 5 above)
Comment (cheenamalhotra) [reply src/main/java/com/microsoft/sqlserver/jdbc/SharedTimer.java]: It's not SQL Server Exception or driver generated exception if this code is reached. This is driver's internal class and the APIs are called internally. So technically if this exception is thrown, it is an illegal state of the driver/application just like a "NullPointerException" that can occur anytime a null value is referenced.

Comment (ulvii) [reply src/main/java/com/microsoft/sqlserver/jdbc/SharedTimer.java]: Is the error message meant to be localized?

Comment (cheenamalhotra) [reply src/main/java/com/microsoft/sqlserver/jdbc/SharedTimer.java]: This is "non-expected" error as it's driver internal implementation. It's not meant to occur.
So no, we wouldn't need to localize it. If this was a driver thrown exception, we would have localized it when this was added.
