### PR TITLE
For invalid error message by passing smalldatetime in ISQLBulkRecord

### LINKED ISSUE #280: Passing smalldatetime via ISQLServerBulkRecord is throwing exception
Passing smalldatetime via ISQLServerBulkRecord throws `Received an invalid column length from the bcp client for colid 1..` By default smalldateime doesn't have scale or precision, passing zero as scale and precision throws the exception.
https://github.com/Microsoft/mssql-jdbc/issues/161#issuecomment-295906312

### PR DESCRIPTION
**Pull request by v-afrafi**
Fixes #280 
For issue #280 also mentioned here. https://github.com/Microsoft/mssql-jdbc/issues/161#issuecomment-295906312

Passing smalldatetime via ISQLBulkRecord without specifiying precision should work. 
Also sending out of range values for character type and binary type should throw proper error rather than `Received an invalid column length from the bcp client for colid 1`.

### CODE REVIEW

File: src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java [hunk 1]
```diff
@@ -2623,6 +2634,10 @@ private void writeColumn(TDSWriter tdsWriter,
                 validateDataTypeConversions(srcColOrdinal, destColOrdinal);
             }
         }
+        //If we are using ISQLBulckRecord and the data we are passing is char type, we need to check the source and dest precision
```
Comment (v-ahibr) [inline src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java]: small typo, should be ISQLBulkRecord

File: src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/ImpISQLServerBulkRecord_IssuesTest.java [hunk 2]
```diff
@@ -0,0 +1,435 @@
...
+            bcOperation.setDestinationTableName(destTable);
+            bcOperation.writeToServer(bData);
+            bcOperation.close();
+        }
+        catch (Exception e) {
+            if (e instanceof SQLServerException) {
+                assertTrue(e.getMessage().contains("The given value of type"), "Invalid Error message: " + e.toString());
+            }
+        }
+        ResultSet rs = stmt.executeQuery("select * from " + destTable);
```
Comment (v-ahibr) [inline src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/ImpISQLServerBulkRecord_IssuesTest.java]: this returns an empty resultset since nothing was inserted. No point in the while loop

File: src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/ImpISQLServerBulkRecord_IssuesTest.java [hunk 3]
```diff
@@ -0,0 +1,435 @@
...
+        BulkDat bData = new BulkDat(variation);
+        String value = "aa";
+        query = "CREATE TABLE " + destTable + " (smallDATA varchar(2))";
+        stmt.executeUpdate(query);
+
+        try {
+            SQLServerBulkCopy bcOperation = new SQLServerBulkCopy(connectionString);
+            bcOperation.setDestinationTableName(destTable);
+            bcOperation.writeToServer(bData);
+            bcOperation.close();
```
Comment (v-ahibr) [inline src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/ImpISQLServerBulkRecord_IssuesTest.java]: after bcOperation.close(), you should force the test to fail with something like:
`fail("BulkCopy executed when it it was expected to fail");`

Once this is done, you can remove the section after the catch that iterates through the resultset

File: src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/ImpISQLServerBulkRecord_IssuesTest.java [hunk 4]
```diff
@@ -0,0 +1,435 @@
...
+        String value = ("1954-05-22 02:44:00.0").toString();
+
+        query = "CREATE TABLE " + destTable + " (smallDATA smalldatetime)";
+        stmt.executeUpdate(query);
+
+        try {
+            SQLServerBulkCopy bcOperation = new SQLServerBulkCopy(connectionString);
+            bcOperation.setDestinationTableName(destTable);
+            bcOperation.writeToServer(bData);
+            bcOperation.close();
```
Comment (v-ahibr) [inline src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/ImpISQLServerBulkRecord_IssuesTest.java]: after bcOperation.close(), you should force the test to fail with something like:
`fail("BulkCopy executed when it it was expected to fail");`

Once this is done, you can remove the section after the catch that iterates through the resultset

File: src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/ImpISQLServerBulkRecord_IssuesTest.java [hunk 5]
```diff
@@ -0,0 +1,435 @@
...
+        }
+        catch (Exception e) {
+            if (e instanceof SQLServerException) {
+                assertTrue(e.getMessage().contains("Conversion failed when converting character string to smalldatetime data type"),
+                        "Invalid Error message: " + e.toString());
+            }
+        }
+        ResultSet rs = stmt.executeQuery("select * from " + destTable);
+        while (rs.next()) {
```
Comment (v-ahibr) [inline src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/ImpISQLServerBulkRecord_IssuesTest.java]: empty resultSet, no point in reading from the table if nothing is in it

File: src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/ImpISQLServerBulkRecord_IssuesTest.java [hunk 6]
```diff
@@ -0,0 +1,435 @@
...
+        variation = "testBinaryColumnAsByte";
+        BulkDat bData = new BulkDat(variation);
+        query = "CREATE TABLE " + destTable + " (col1 binary(5))";
+        stmt.executeUpdate(query);
+
+        try {
+            SQLServerBulkCopy bcOperation = new SQLServerBulkCopy(connectionString);
+            bcOperation.setDestinationTableName(destTable);
+            bcOperation.writeToServer(bData);
+            bcOperation.close();
```
Comment (v-ahibr) [inline src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/ImpISQLServerBulkRecord_IssuesTest.java]: after bcOperation.close(), you should force the test to fail with something like:
`fail("BulkCopy executed when it it was expected to fail");`

File: src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/ImpISQLServerBulkRecord_IssuesTest.java [hunk 7]
```diff
@@ -0,0 +1,435 @@
...
+        variation = "testBinaryColumnAsString";
+        BulkDat bData = new BulkDat(variation);
+        query = "CREATE TABLE " + destTable + " (col1 binary(5))";
+        stmt.executeUpdate(query);
+
+        try {
+            SQLServerBulkCopy bcOperation = new SQLServerBulkCopy(connectionString);
+            bcOperation.setDestinationTableName(destTable);
+            bcOperation.writeToServer(bData);
+            bcOperation.close();
```
Comment (v-ahibr) [inline src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/ImpISQLServerBulkRecord_IssuesTest.java]: after bcOperation.close(), you should force the test to fail with something like:
`fail("BulkCopy executed when it it was expected to fail");`

File: src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java [hunk 8]
```diff
@@ -1240,6 +1240,11 @@ private String getDestTypeFromSrcType(int srcColIndx,
             int destColIndx,
             TDSWriter tdsWriter) throws SQLServerException {
         boolean isStreaming;
+        /**
+         * The maximum temporal precision we can send when using varchar(precision) in bulkcommand, to send a smalldatetime/datetime 
+         * value.
+         */
+        int sourceBulkRecordTemporalMaxPrecision = 50;
```
Comment (v-nisidh) [inline src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java]: is value of sourceBulkRecordTemporalMaxPrecision constant? if so then can we use final modifier for mentioned variable? better class level `static final`

Comment (v-afrafi) [inline src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java]: done
