### PR TITLE
Fix | Connection pool proxy with delayLoadingLobs

### LINKED ISSUE #1401: Regression in 8.4.0; SQLServerResultSet; SQLServerConnection vs SQLServerConnectionPoolProxy
## Driver version
8.4.0

## Problem description
Caused by: java.lang.ClassCastException: com.microsoft.sqlserver.jdbc.SQLServerConnectionPoolProxy incompatible with com.microsoft.sqlserver.jdbc.SQLServerConnection 
at com.microsoft.sqlserver.jdbc.SQLServerResultSet.configureLobs(SQLServerResultSet.java:2085) 
at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getClob(SQLServerResultSet.java:2825) 
at com.ibm.ws.rsadapter.jdbc.WSJdbcResultSet.getClob(WSJdbcResultSet.java:750) 
at org.hibernate.type.descriptor.sql.ClobTypeDescriptor$1.doExtract(ClobTypeDescriptor.java:44) 
at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47) 
...

## Analysis
https://github.com/microsoft/mssql-jdbc/commit/54c67488d881f7075c4632967ec0d5a558138c69#diff-e5880682be515f702f2a448d2dbcdedf introduced the new method "configureLobs".
configureLobs uses hardcoded SQLServerConnection. But in some usecases (java-applicationserver?) the connection is not an instance of SQLServerConnection but of SQLServerConnectionPoolProxy. --> ClassCastException

image

### PR DESCRIPTION
**Pull request by rene-ye**
Fixes #1401

### CODE REVIEW

File: src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java [hunk 1]
```diff
@@ -702,9 +702,13 @@ byte getServerSupportedDataClassificationVersion() {
     // Boolean that indicates whether LOB objects created by this connection should be loaded into memory
     private boolean delayLoadingLobs = SQLServerDriverBooleanProperty.DELAY_LOADING_LOBS.getDefaultValue();
 
-    boolean getDelayLoadingLobs() {
+    public boolean getDelayLoadingLobs() {
```
Comment (lilgreenbird) [inline src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java:705]: public methods should have description header

File: src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java [hunk 2]
```diff
@@ -702,9 +702,13 @@ byte getServerSupportedDataClassificationVersion() {
...
         return delayLoadingLobs;
     }
+    
+    public void setDelayLoadingLobs(boolean b) {
```
Comment (lilgreenbird) [inline src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java:709]: header

File: src/test/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionTest.java [hunk 3]
```diff
@@ -434,7 +437,7 @@ public void testClosedConnection() throws SQLException {
         } catch (SQLServerException e) {
             assertEquals(e.getMessage(), TestResource.getResource("R_connectionIsClosed"),
                     TestResource.getResource("R_wrongExceptionMessage"));
-          assertEquals("08S01", e.getSQLState(), TestResource.getResource("R_wrongSqlState"));
+            assertEquals("08S01", e.getSQLState(), TestResource.getResource("R_wrongSqlState"));
```
Comment (lilgreenbird) [inline src/test/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionTest.java:440]: is there a tab here?? (same in line 575)

File: src/test/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionTest.java [hunk 4]
```diff
@@ -569,7 +572,7 @@ public void testClientConnectionId() throws Exception {
             } catch (SQLException e) {
                 assertEquals(e.getMessage(), TestResource.getResource("R_connectionIsClosed"),
```
Comment (lilgreenbird) [inline src/test/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionTest.java:573]: expected is 1st param

File: src/test/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionTest.java (hunk 3 above)
Comment (rene-ye) [reply src/test/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionTest.java:440]: It wasn't formatted properly, it was off by 2 spaces.

File: src/test/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionTest.java (hunk 4 above)
Comment (rene-ye) [reply src/test/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionTest.java:573]: Not a part of this PR.

File: src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java (hunk 1 above)
Comment (ulvii) [reply src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java:705]: Shouldn't you override here?

File: src/test/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionTest.java (hunk 4 above)
Comment (ulvii) [inline src/test/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionTest.java:573]:
```suggestion
                assertEquals(TestResource.getResource("R_connectionIsClosed", e.getMessage()),

```

File: src/main/java/com/microsoft/sqlserver/jdbc/ISQLServerConnection.java [hunk 5]
```diff
@@ -358,4 +358,19 @@ CallableStatement prepareCall(String sql, int nType, int nConcur, int nHold,
      *        boolean value for 'useFmtOnly'.
      */
     void setUseFmtOnly(boolean useFmtOnly);
+    
+    /**
+     * Returns the current flag value for delayLoadingLobs.
+     *
+     * @return 'delayLoadingLobs' property value.
+     */
+    boolean getDelayLoadingLobs();
```
Comment (peterbae) [inline src/main/java/com/microsoft/sqlserver/jdbc/ISQLServerConnection.java:367]: Wouldn't this be a breaking change? Since we're adding new methods to a public interface, any user who has been using ISQLServerConnection to implement their own connection class would be getting a compilation error now.

File: src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java (hunk 1 above)
Comment (rene-ye) [reply src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java:705]: Well there's no previous implementation to get confused about, so the only reason to do it would be for "commenting".

File: src/main/java/com/microsoft/sqlserver/jdbc/ISQLServerConnection.java (hunk 5 above)
Comment (rene-ye) [reply src/main/java/com/microsoft/sqlserver/jdbc/ISQLServerConnection.java:367]: Technically I guess, I'm not sure if anyone actually implements our interfaces.

File: src/test/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionTest.java (hunk 4 above)
Comment (lilgreenbird) [reply src/test/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionTest.java]: yeah, but it's in the same place, why not fix?

**Comment by rene-ye** [comment]
[mssql-jdbc-8.5.0-SNAPSHOT.jre8-preview.jar.zip](https://github.com/microsoft/mssql-jdbc/files/5092185/mssql-jdbc-8.5.0-SNAPSHOT.jre8-preview.jar.zip)

Nullptr fix.
